/**
 * Journey Combinations sample data
 * Mirrors the LOA configuration spreadsheet columns.
 */
window.JOURNEY_DATA = {
  leavePatterns: ["Continuous", "Intermittent", "Reduced Schedule"],
  leaveReasons: [
    "Care for a Family Member",
    "Employee Own Serious Health Condition",
    "Bonding with Newborn or Adopted Child",
    "Military Caregiver",
    "Qualifying Exigency"
  ],
  universalFamilyCodes: [
    "FAMILY_BONDING",
    "EMPLOYEE_HEALTH",
    "MILITARY_CAREGIVER",
    "QUALIFYING_EXIGENCY"
  ],
  payBuckets: ["SICK", "FPD", "FLOAT", "PTO", "UNPAID"],
  selectionModes: ["ALL_OR_SELECTED", "SYSTEM_REMAINDER", "SYSTEM_GENERATED"],
  trackingBuckets: ["FMLA", "NON_FMLA"],
  hoursModes: [
    "User selected hours or all available balance",
    "Remaining hours only",
    "System generated remainder"
  ],

  combinations: [
    {
      journeyCombinationId: "OR_LOA_1",
      journeyCombinationKey: "Continuous-Care for a Family Member",
      leavePattern: "Continuous",
      leaveReason: "Care for a Family Member",
      universalLoaFamilyCode: "FAMILY_BONDING",
      status: "Active",
      buckets: [
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Sick Family Care or Bonding FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_SICK_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Sick/ESL",
          primaryPtypcdNw: "BNR",
          alternatePtypcdCandidatesNw: "SCB",
          derivedPayCd: "427, 443",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "NON_FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Sick Family Care or Bonding Non-FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_SICK_NONFMLA_01",
          kptimeAbsenceType: "KPTIME - Non-FMLA - Sick/ESL",
          primaryPtypcdNw: "SCK",
          alternatePtypcdCandidatesNw: "ESL, IND, INF, PSF, SCL",
          derivedPayCd: "393, 400, 254, 258",
          fmlaFlagAuthoritative: "No",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "FPD",
          bucketSequence: 20,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Fixed Paid Days Family Care FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_FPD_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Fixed Paid Days",
          primaryPtypcdNw: "FPN",
          alternatePtypcdCandidatesNw: "FPP",
          derivedPayCd: "439",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "FPD",
          bucketSequence: 20,
          fmlaTrackingBucket: "NON_FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Fixed Paid Days Family Care Non-FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_FPD_NONFMLA_01",
          kptimeAbsenceType: "KPTIME - Non-FMLA - Fixed Paid Days",
          primaryPtypcdNw: "FPD",
          alternatePtypcdCandidatesNw: "FPS, FPL",
          derivedPayCd: "482",
          fmlaFlagAuthoritative: "No",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "FLOAT",
          bucketSequence: 30,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Floating Holiday Family Care FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_FLOAT_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Floating Holiday",
          primaryPtypcdNw: "FHN",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "323",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "FLOAT",
          bucketSequence: 30,
          fmlaTrackingBucket: "NON_FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Floating Holiday Family Care Non-FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_FLOAT_NONFMLA_01",
          kptimeAbsenceType: "KPTIME - Non-FMLA - Floating Holiday",
          primaryPtypcdNw: "FHL",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "323",
          fmlaFlagAuthoritative: "No",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "PTO",
          bucketSequence: 40,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_REMAINDER",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence PTO Family Care or Bonding FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_PTO_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - PTO",
          primaryPtypcdNw: "PTH",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "312",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "Remaining hours only"
        },
        {
          payBucketCode: "PTO",
          bucketSequence: 40,
          fmlaTrackingBucket: "NON_FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_REMAINDER",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence PTO Family Care or Bonding Non-FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_PTO_NONFMLA_01",
          kptimeAbsenceType: "KPTIME - Non-FMLA - PTO",
          primaryPtypcdNw: "PTO",
          alternatePtypcdCandidatesNw: "PTF",
          derivedPayCd: "310",
          fmlaFlagAuthoritative: "No",
          planSelectionRequired: "Y",
          hoursMode: "Remaining hours only"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 50,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Unpaid Family Care or Bonding FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_UNPAID_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Unpaid LOA",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "900",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 50,
          fmlaTrackingBucket: "NON_FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Unpaid Family Care or Bonding Non-FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_UNPAID_NONFMLA_01",
          kptimeAbsenceType: "KPTIME - Non-FMLA - Unpaid LOA",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "901",
          fmlaFlagAuthoritative: "No",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        }
      ]
    },
    {
      journeyCombinationId: "OR_LOA_2",
      journeyCombinationKey: "Continuous-Employee Own Serious Health Condition",
      leavePattern: "Continuous",
      leaveReason: "Employee Own Serious Health Condition",
      universalLoaFamilyCode: "EMPLOYEE_HEALTH",
      status: "Active",
      buckets: [
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Sick Employee Health FMLA",
          universalAbsenceTypeId: "EMPLOYEE_HEALTH_SICK_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Sick/ESL",
          primaryPtypcdNw: "SCK",
          alternatePtypcdCandidatesNw: "ESL, IND, INF, PSF, SCL",
          derivedPayCd: "393, 400",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "NON_FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Sick Employee Health Non-FMLA",
          universalAbsenceTypeId: "EMPLOYEE_HEALTH_SICK_NONFMLA_01",
          kptimeAbsenceType: "KPTIME - Non-FMLA - Sick/ESL",
          primaryPtypcdNw: "SCK",
          alternatePtypcdCandidatesNw: "ESL, IND, INF",
          derivedPayCd: "254, 258",
          fmlaFlagAuthoritative: "No",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "PTO",
          bucketSequence: 20,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_REMAINDER",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence PTO Employee Health FMLA",
          universalAbsenceTypeId: "EMPLOYEE_HEALTH_PTO_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - PTO",
          primaryPtypcdNw: "PTH",
          alternatePtypcdCandidatesNw: "PTO",
          derivedPayCd: "312",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "Remaining hours only"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 30,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Unpaid Employee Health FMLA",
          universalAbsenceTypeId: "EMPLOYEE_HEALTH_UNPAID_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Unpaid LOA",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "900",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        }
      ]
    },
    {
      journeyCombinationId: "OR_LOA_3",
      journeyCombinationKey: "Intermittent-Care for a Family Member",
      leavePattern: "Intermittent",
      leaveReason: "Care for a Family Member",
      universalLoaFamilyCode: "FAMILY_BONDING",
      status: "Active",
      buckets: [
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Intermittent Sick Family Care FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_SICK_INT_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Sick/ESL Intermittent",
          primaryPtypcdNw: "BNR",
          alternatePtypcdCandidatesNw: "SCB",
          derivedPayCd: "427",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "PTO",
          bucketSequence: 20,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_REMAINDER",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Intermittent PTO Family Care FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_PTO_INT_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - PTO Intermittent",
          primaryPtypcdNw: "PTH",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "312",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "Remaining hours only"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 30,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Intermittent Unpaid Family Care FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_UNPAID_INT_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Unpaid Intermittent",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "900",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        }
      ]
    },
    {
      journeyCombinationId: "OR_LOA_4",
      journeyCombinationKey: "Continuous-Bonding with Newborn or Adopted Child",
      leavePattern: "Continuous",
      leaveReason: "Bonding with Newborn or Adopted Child",
      universalLoaFamilyCode: "FAMILY_BONDING",
      status: "Draft",
      buckets: [
        {
          payBucketCode: "FPD",
          bucketSequence: 10,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Fixed Paid Days Bonding FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_FPD_BOND_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Fixed Paid Days",
          primaryPtypcdNw: "FPN",
          alternatePtypcdCandidatesNw: "FPP",
          derivedPayCd: "439",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "PTO",
          bucketSequence: 20,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_REMAINDER",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence PTO Bonding FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_PTO_BOND_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - PTO",
          primaryPtypcdNw: "PTH",
          alternatePtypcdCandidatesNw: "PTO, PTF",
          derivedPayCd: "312, 310",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "Remaining hours only"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 30,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Unpaid Bonding FMLA",
          universalAbsenceTypeId: "FAMILY_BONDING_UNPAID_BOND_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Unpaid LOA",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "900",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        }
      ]
    },
    {
      journeyCombinationId: "OR_LOA_5",
      journeyCombinationKey: "Reduced Schedule-Employee Own Serious Health Condition",
      leavePattern: "Reduced Schedule",
      leaveReason: "Employee Own Serious Health Condition",
      universalLoaFamilyCode: "EMPLOYEE_HEALTH",
      status: "Active",
      buckets: [
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Reduced Schedule Sick Employee Health FMLA",
          universalAbsenceTypeId: "EMPLOYEE_HEALTH_SICK_RS_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Sick Reduced",
          primaryPtypcdNw: "SCK",
          alternatePtypcdCandidatesNw: "ESL, IND",
          derivedPayCd: "393",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 20,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Reduced Schedule Unpaid Employee Health FMLA",
          universalAbsenceTypeId: "EMPLOYEE_HEALTH_UNPAID_RS_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Unpaid Reduced",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "900",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        }
      ]
    },
    {
      journeyCombinationId: "OR_LOA_6",
      journeyCombinationKey: "Continuous-Military Caregiver",
      leavePattern: "Continuous",
      leaveReason: "Military Caregiver",
      universalLoaFamilyCode: "MILITARY_CAREGIVER",
      status: "Inactive",
      buckets: [
        {
          payBucketCode: "SICK",
          bucketSequence: 10,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "ALL_OR_SELECTED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Sick Military Caregiver FMLA",
          universalAbsenceTypeId: "MILITARY_CAREGIVER_SICK_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Sick Military",
          primaryPtypcdNw: "SCK",
          alternatePtypcdCandidatesNw: "ESL",
          derivedPayCd: "393",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "User selected hours or all available balance"
        },
        {
          payBucketCode: "PTO",
          bucketSequence: 20,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "Y",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_REMAINDER",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence PTO Military Caregiver FMLA",
          universalAbsenceTypeId: "MILITARY_CAREGIVER_PTO_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - PTO Military",
          primaryPtypcdNw: "PTH",
          alternatePtypcdCandidatesNw: "PTO",
          derivedPayCd: "312",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "Y",
          hoursMode: "Remaining hours only"
        },
        {
          payBucketCode: "UNPAID",
          bucketSequence: 30,
          fmlaTrackingBucket: "FMLA",
          userSelectable: "N",
          mandatoryUsage: "N",
          allowedSelectionMode: "SYSTEM_GENERATED",
          waitPeriodApplies: "N",
          waitSubstituteBucket: "",
          targetHcmAbsenceTypeName: "Leave of Absence Unpaid Military Caregiver FMLA",
          universalAbsenceTypeId: "MILITARY_CAREGIVER_UNPAID_FMLA_01",
          kptimeAbsenceType: "KPTIME - FMLA - Unpaid Military",
          primaryPtypcdNw: "LOA",
          alternatePtypcdCandidatesNw: "",
          derivedPayCd: "900",
          fmlaFlagAuthoritative: "yes",
          planSelectionRequired: "N",
          hoursMode: "System generated remainder"
        }
      ]
    }
  ]
};
